variables:

  # Global
  ap_vm_image: windows-2019

  location: eastus 
  prefix: fasthack 
  postfix: uc3
  environment: dev
  objectID: 'bfb89611-c0c4-4d47-a934-dcd6a960b148'

  # Azure DevOps 
  ado_service_connection_rg: Azure-ARM-Dev-SAPA
  # github
  gihub_repo_name: "Azure/fta-Catalytics"

  # IaC
  baseName: $(prefix)$(postfix)$(environment)
  resourceGroupName: AP4-$(baseName)-RG
  storageAccountName: $(prefix)st$(postfix)$(environment)
  dataLakeAccountName: $(prefix)adl$(postfix)$(environment)
  sqlServerName: $(prefix)-sql-$(postfix)-$(environment)
  databaseName: sampledb
  synapseWorkspace: $(prefix)-synapse-$(postfix)-$(environment)
  synapsedatalakegen2name: $(prefix)adlssyn$(postfix)$(environment)
  keyVaultName: $(prefix)-akv-$(postfix)-$(environment)

